spring.application.name=jpa
spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore-jpa
spring.datasource.username=postgres
spring.datasource.password=1234
spring.jpa.hibernate.ddl-auto=update

spring.jba.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.show-sql=true
